### ISSUE TITLE
Would you mind sharing a bit about this project?

### ISSUE THREAD

**Issue by MendyBerger** [csobrinho/hydroponics#1]
I stumbled upon this project, and the idea of a self managed hydroponics system sounded really interesting to me, but I cant seem to find any information about this project. Would you mind sharing a bit more information, like: what sensors it uses, what its capable of doing, with what types of plants can it work, maybe some images if you have, etc.?

**Comment by bradq** [comment]
I'm taking a look via [Reddit](https://www.reddit.com/r/Hydroponics/comments/i9xhkp/finally_added_remotely_controlled_nutrientsph/g1i65n7/). Their post history has a pretty in-depth discussion of setup. Probably easier to engage there if you're more interested in setup than the automation code.

**Comment by MendyBerger** [comment]
Thanks @bradq will check it out

**Comment by csobrinho** [comment]
Hey folks, sorry for the late reply. For some reason gmail always hide the notifications from github so I miss them.

So I currently have a prototype with:
 - 2x ph probes (one from Sensorex, another from Atlas)
 - 2x ec probes (two from Sensorex)
 - 5x Atlas modules (2 ph, 2 ec, 1 RTD)
 - 16 bit I2C io expander
 - 2x eTape Liquid Level sensor
 - 1x 4ch adc ADS1115
 - 1x BME280
 - 1x 2.7" parallel screen
 - 1x button
 - 8x peristaltic pumps
 - 4x solenoid valves
 - 2x 8bit relay module

The main reason why I haven't ordered a PCB is because I'm replacing the I2S parallel screen with a 4" SPI screen at 80 MHz. That means I had to write a new driver for the ST7796S (that is done btw) but I also need to change the schematics and that will release a bunch of IO ports.

Things I want to add before I order the PCB:
 - replace the screen with an SPI version
 - add a 1-wire port
 - add a CAN/(or an RS485) transceiver
 - replace the I2C expander with a 24 bit like the [TCA6424A](https://www.ti.com/product/TCA6424A) or a 40 bit like the [PCA9698BS](https://www.nxp.com/part/PCA9698BS#/)
 - add a buzzer
 - add screen backlight control (on/off,maybe PWM?)
 - add rotary button for better UI
 - add 1-3 servo output. Need at least one for the output of the pumps to go to tank A or B.
 - replace the ADC for something with more channels or add an extra one.

After I figure **all that** or part of it, then I'll create a PCB and start iterating on it. I also activated the discussion feature on github so that we can start talking more about this. You can reach me there or via reddit.

**Comment by MendyBerger** [comment]
Thanks @csobrinho for the update, Super cool!
